version: '3.8'

services:
  leonidas_db:
    image: postgres:12.7
    container_name: leonidas_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
      - APP_DB_SCHEMA_NAME=${APP_DB_SCHEMA_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ${DB_FILE_SYSTEM_STORAGE}:/var/lib/postgresql
      - ${DB_FILE_SYSTEM_STORAGE}/data:/var/lib/postgresql/data
      - ./postgres-database/init-scripts:/docker-entrypoint-initdb.d
  leonidas_bh:
    image: viktorvx/leonidas-bh:latest
    container_name: leonidas_bh
    depends_on:
      - leonidas_db
    environment:
      - leonidas.db.url=jdbc:postgresql://leonidas_db:${LEONIDAS_DB_PORT}/${LEONIDAS_DB_NAME}
      - leonidas.db.user.name=${LEONIDAS_DB_USER_NAME}
      - leonidas.db.user.password=${LEONIDAS_DB_USER_PASSWORD}
      - leonidas.db.schema=${LEONIDAS_DB_SCHEMA}
    ports:
      - '8080:8080'