version: '3.8'

services:
  database:
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
      - APP_DB_SCHEMA_NAME=${APP_DB_SCHEMA_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ${DB_FILE_SYSTEM_STORAGE}:/var/lib/postgresql
      - ${DB_FILE_SYSTEM_STORAGE}/data:/var/lib/postgresql/data
      - ./postgres-database/init-scripts:/docker-entrypoint-initdb.d